-- Indexes
CREATE INDEX I_CUSTOMER_1 					ON CRPROFL.CUSTOMER (CUSTOMER_ID, line_of_business);
CREATE INDEX I_CUSTOMER_1 					ON customer(customer_id, line_of_business);

CREATE INDEX I_CUSTOMER_2 					ON CRPROFL.CUSTOMER (PARTY_ID);

CREATE INDEX I_PARTY_IDENTIFICATION_1 		ON CRPROFL.PARTY_IDENTIFICATION (PARTY_ID) INCLUDE (IDENTIFICATON_ID);
CREATE INDEX I_IDENTIFICATION_CHAR_1 		ON CRPROFL.IDENTIFICATION_CHAR (IDENTIFICATON_ID) INCLUDE (KEY);
CREATE INDEX I_IDENTIFICATION_CHAR_HASH_1 	ON CRPROFL.IDENTIFICATION_CHAR_HASH (IDENTIFICATON_ID) INCLUDE (KEY);
CREATE INDEX I_PARTY_CONTACT_MEDIUM_1 		ON CRPROFL.PARTY_CONTACT_MEDIUM (PARTY_ID);
CREATE INDEX I_CREDIT_PROFILE_1 			ON CRPROFL.CREDIT_PROFILE (CREDIT_PROFILE_ID_LEGACY);
CREATE INDEX I_CREDIT_WARNING_HISTORY_1 	ON CRPROFL.CREDIT_WARNING_HISTORY (CREDIT_PROFILE_ID);
CREATE INDEX I_CREDIT_WARNING_HISTORY_2 	ON CRPROFL.CREDIT_WARNING_HISTORY (WARNING_LEGACY_ID);
CREATE INDEX I_PROD_QUAL_1 	ON CRPROFL.PROD_QUAL (CREDIT_PROFILE_ID);
CREATE INDEX I_PROD_QUAL_2 	ON CRPROFL.PROD_QUAL (product_qual_legacy_id);
CREATE INDEX I_individual_birth_date ON crprofl.individual (birth_date);


CREATE INDEX I_READDB_SYNC_STATUS_1 		ON CRPROFL.READDB_SYNC_STATUS (NEED_TO_SYNC);

-- xconversin tables 
CREATE INDEX I_X_CREDIT_PROFILE_1 ON CRPROFL.X_CREDIT_PROFILE (CUSTOMER_ID);
CREATE INDEX I_X_WARNING_1 ON CRPROFL.X_WARNING (CUSTOMER_ID);
CREATE INDEX I_X_SYNC_STATUS_1 ON CRPROFL.X_SYNC_STATUS (CUSTOMER_ID);
CREATE INDEX I_X_ASSESSMENT_1 ON CRPROFL.X_ASSESSMENT (CUSTOMER_ID);
CREATE INDEX I_X_PROD_QUAL ON CRPROFL.X_PRODQUAL (CUSTOMER_ID);






drop index CRPROFL.I_CUSTOMER_1;
drop index CRPROFL.I_CUSTOMER_2;
drop index CRPROFL.I_PARTY_IDENTIFICATION_1;
drop index CRPROFL.I_IDENTIFICATION_CHAR_1;
drop index CRPROFL.I_IDENTIFICATION_CHAR_HASH_1;
drop index CRPROFL.I_PARTY_CONTACT_MEDIUM_1;
drop index CRPROFL.I_CREDIT_PROFILE_1;
drop index CRPROFL.I_CREDIT_WARNING_HISTORY_1;
drop index CRPROFL.I_CREDIT_WARNING_HISTORY_2;
drop index CRPROFL.I_PROD_QUAL_1;
drop index CRPROFL.I_PROD_QUAL_2;
drop index CRPROFL.I_individual_birth_date;
drop index CRPROFL.I_READDB_SYNC_STATUS_1;

