-------------------------------------------------------------------
-- Script to create schema, tables, constraints.
--
-------------------------------------------------------------------

-- Schema
CREATE SCHEMA CRPROFL;

-- UUID extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Tables
CREATE TABLE CRPROFL.PARTY (
  PARTY_ID UUID DEFAULT uuid_generate_v4(),
  PARTY_TYPE VARCHAR NOT NULL,
  PARTY_ROLE VARCHAR NOT NULL,
  CREATED_BY VARCHAR,
  CREATED_TS TIMESTAMP DEFAULT NOW(),
  UPDATED_BY VARCHAR,
  UPDATED_TS TIMESTAMP DEFAULT NOW(),
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  VERSION INT DEFAULT 1,
  CONSTRAINT PK_PRTY_PARTY_ID PRIMARY KEY (PARTY_ID)
);

CREATE TABLE CRPROFL.INDIVIDUAL (
  PARTY_ID UUID NOT NULL ,
  BIRTH_DATE DATE,
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  CREATED_BY VARCHAR,
  CREATED_TS TIMESTAMP DEFAULT NOW(),
  UPDATED_BY VARCHAR,
  UPDATED_TS TIMESTAMP DEFAULT NOW(),
  VERSION INT DEFAULT 1,
  CONSTRAINT UK_INDV_PARTY_ID UNIQUE (PARTY_ID),
  CONSTRAINT FK_INDV_PARTY_ID FOREIGN KEY (PARTY_ID) REFERENCES CRPROFL.PARTY (PARTY_ID)
);

CREATE TABLE CRPROFL.ORGANIZATION (
  PARTY_ID UUID NOT NULL,
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  CREATED_BY VARCHAR,
  CREATED_TS TIMESTAMP DEFAULT NOW(),
  UPDATED_BY VARCHAR,
  UPDATED_TS TIMESTAMP DEFAULT NOW(),
  VERSION INT DEFAULT 1,
  CONSTRAINT UK_ORGN_PARTY_ID UNIQUE (PARTY_ID),
  CONSTRAINT FK_ORGN_PARTY_ID FOREIGN KEY (PARTY_ID) REFERENCES CRPROFL.PARTY (PARTY_ID)
);

CREATE TABLE CRPROFL.PARTY_IDENTIFICATION (
  IDENTIFICATON_ID UUID DEFAULT uuid_generate_v4(),
  PARTY_ID UUID NOT NULL,
  ID_TYPE VARCHAR NOT NULL,
  VALID_START_TS TIMESTAMP,
  VALID_END_TS TIMESTAMP,
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  CREATED_BY VARCHAR,
  CREATED_TS TIMESTAMP DEFAULT NOW(), 
  UPDATED_BY VARCHAR,
  UPDATED_TS TIMESTAMP DEFAULT NOW(),
  VERSION INT DEFAULT 1,
  CONSTRAINT PK_PRID_IDENTIFICATON_ID PRIMARY KEY (IDENTIFICATON_ID),
  CONSTRAINT FK_PRID_PARTY_ID FOREIGN KEY (PARTY_ID) REFERENCES CRPROFL.PARTY (PARTY_ID)
);

--a Reference table . it is initialized during DDL execution to create db tables.
CREATE TABLE CRPROFL.IDENTIFICATION_ATTRIBUTES (
  ATTRIBUTE_NAME VARCHAR,
  IS_ENCRYPTED BOOLEAN DEFAULT FALSE,
  CREATED_BY VARCHAR,
  CREATED_TS TIMESTAMP DEFAULT NOW(), 
  UPDATED_BY VARCHAR,
  UPDATED_TS TIMESTAMP DEFAULT NOW(),
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  VERSION INT DEFAULT 1,
  CONSTRAINT PK_IDAT_ATTRIBUTE_NAME PRIMARY KEY (ATTRIBUTE_NAME)
);

CREATE TABLE CRPROFL.IDENTIFICATION_CHAR (
  IDENTIFICATION_CHAR_ID UUID DEFAULT uuid_generate_v4(),
  IDENTIFICATON_ID UUID NOT NULL,
  KEY VARCHAR NOT NULL, 
  VALUE TEXT NOT NULL,
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  CREATED_BY VARCHAR,
  CREATED_TS TIMESTAMP DEFAULT NOW(),
  UPDATED_BY VARCHAR,
  UPDATED_TS TIMESTAMP DEFAULT NOW(),
  VERSION INT DEFAULT 1,
  CONSTRAINT PK_IDCH_IDENTIFICATION_CHAR_ID PRIMARY KEY (IDENTIFICATION_CHAR_ID),
  CONSTRAINT FK_IDCH_IDENTIFICATION_ID FOREIGN KEY (IDENTIFICATON_ID) REFERENCES CRPROFL.PARTY_IDENTIFICATION (IDENTIFICATON_ID),
  CONSTRAINT FK_IDCH_KEY FOREIGN KEY (KEY) REFERENCES CRPROFL.IDENTIFICATION_ATTRIBUTES (ATTRIBUTE_NAME)
);

CREATE TABLE CRPROFL.IDENTIFICATION_CHAR_HASH (
  IDENTIFICATION_HASH_ID UUID DEFAULT uuid_generate_v4(),
  IDENTIFICATON_ID UUID NOT NULL,
  KEY VARCHAR NOT NULL,
  VALUE TEXT NOT NULL,
  HASH_TYPE VARCHAR NOT NULL,
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  CREATED_BY VARCHAR,
  CREATED_TS TIMESTAMP DEFAULT NOW(),
  UPDATED_BY VARCHAR,
  UPDATED_TS TIMESTAMP DEFAULT NOW(),
  VERSION INT DEFAULT 1,
  CONSTRAINT PK_IDHS_IDENTIFICATION_HASH_ID PRIMARY KEY (IDENTIFICATION_HASH_ID),
  CONSTRAINT FK_IDHS_IDENTIFICATION_ID FOREIGN KEY (IDENTIFICATON_ID) REFERENCES CRPROFL.PARTY_IDENTIFICATION (IDENTIFICATON_ID),
  CONSTRAINT FK_IDHS_KEY FOREIGN KEY (KEY) REFERENCES CRPROFL.IDENTIFICATION_ATTRIBUTES (ATTRIBUTE_NAME)
);

CREATE TABLE CRPROFL.PARTY_CONTACT_MEDIUM (
  CONTACT_MEDIUM_ID UUID DEFAULT uuid_generate_v4(),
  PARTY_ID UUID NOT NULL,
  PREFFERED BOOLEAN DEFAULT FALSE,
  MEDIUM_TYPE VARCHAR,
  VALID_START_TS TIMESTAMP,
  VALID_END_TS TIMESTAMP,
  CONTACT_TYPE VARCHAR,
  STREET1 VARCHAR,
  STREET2 VARCHAR,
  STREET3 VARCHAR,
  STREET4 VARCHAR,
  STREET5 VARCHAR,
  CITY VARCHAR,
  STATE_PROVINCE_CODE VARCHAR,
  POST_CODE VARCHAR,
  COUNTRY_CODE VARCHAR,
  EMAIL VARCHAR,
  FAX_NUMBER VARCHAR,
  PHONE_NUMBER VARCHAR,
  CREATED_BY VARCHAR,
  CREATED_TS TIMESTAMP DEFAULT NOW(),
  UPDATED_BY VARCHAR,
  UPDATED_TS TIMESTAMP DEFAULT NOW(),
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  VERSION INT DEFAULT 1,
  CONSTRAINT PK_PRCN_CONTACT_MEDIUM_ID PRIMARY KEY (CONTACT_MEDIUM_ID),
  CONSTRAINT FK_PACO_PARTY_ID FOREIGN KEY (PARTY_ID) REFERENCES CRPROFL.PARTY (PARTY_ID)
);

CREATE TABLE CRPROFL.CUSTOMER (
  CREDIT_PROFILE_CUSTOMER_ID UUID DEFAULT uuid_generate_v4(),
  CUSTOMER_ID BIGINT NOT NULL,
  PARTY_ID UUID NOT NULL,
  LINE_OF_BUSINESS VARCHAR,
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  CREATED_BY VARCHAR,
  CREATED_TS TIMESTAMP DEFAULT NOW(),
  UPDATED_BY VARCHAR,
  UPDATED_TS TIMESTAMP DEFAULT NOW(),
  VERSION INT DEFAULT 1,
  CONSTRAINT PK_CREDIT_PROFILE_CUSTOMER_ID PRIMARY KEY (CREDIT_PROFILE_CUSTOMER_ID),
  CONSTRAINT FK_CUST_PARTY_ID FOREIGN KEY (PARTY_ID) REFERENCES CRPROFL.PARTY (PARTY_ID)
);

CREATE TABLE CRPROFL.CREDIT_PROFILE (
  CREDIT_PROFILE_ID UUID DEFAULT uuid_generate_v4(),
  CREDIT_PROFILE_ID_LEGACY BIGINT,
  CREDIT_PROFILE_TS TIMESTAMP,
  AGENCY_DECISION_CODE VARCHAR,
  AGENCY_DECISION_DESC VARCHAR,
  CREDIT_SCORE TEXT,
  CREDIT_SCORE_TYPE_CODE VARCHAR,
  CREDIT_RISK_RATING TEXT,
  RISK_LEVEL_DECISION_CODE TEXT,
  RISK_LEVEL_TS TIMESTAMP,
  CLP_RATE_PLAN_AMT NUMERIC(9,2),
  CLP_CONTRACT_TERM INT,
  CLP_CREDIT_LIMIT_AMT NUMERIC(9,2),
  SECURITY_DEP_AMT NUMERIC(9,2),
  CREDIT_PROGRAM_NAME VARCHAR,
  CREDIT_CLASS_CODE TEXT,
  CREDIT_CLASS_TS TIMESTAMP,
  CREDIT_DECISION_CODE TEXT,
  CREDIT_DECISION_TS TIMESTAMP,
  CREDIT_ASSESSMENT_ID BIGINT,
  VALID_START_TS TIMESTAMP,
  VALID_END_TS TIMESTAMP,
  CREATED_BY VARCHAR,
  CREATED_TS TIMESTAMP DEFAULT NOW(),
  UPDATED_BY VARCHAR,
  UPDATED_TS TIMESTAMP DEFAULT NOW(),
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  VERSION INT DEFAULT 1,  
  APPLICATION_SUB_PROV_CD VARCHAR,
  CREDIT_CHECK_CONSENT_CD VARCHAR,
  LINE_OF_BUSINESS VARCHAR,
  CREDIT_PROFILE_STATUS_CD VARCHAR,
  CREDIT_PROFILE_STATUS_TS VARCHAR;  
  CONSTRAINT PK_CRPF_CREDIT_PROFILE_ID PRIMARY KEY(CREDIT_PROFILE_ID)
);

CREATE TABLE CRPROFL.CREDIT_WARNING_HISTORY (
  WARNING_ID UUID DEFAULT uuid_generate_v4(),
  WARNING_LEGACY_ID BIGINT,
  CREDIT_PROFILE_ID UUID NOT NULL,
  WARNING_STATUS_CD TEXT,
  WARNING_CD TEXT,
  WARNING_CATEGORY_CD TEXT,
  WARNING_TYPE_CD TEXT,
  WARNING_ITEM_TYPE_CD TEXT,
  EXTERNAL_REFERENCE_ID VARCHAR,
  RESOLVED_FLAG BOOLEAN,
  WARNING_DETECTION_TS TIMESTAMP,
  WARNING_ACCEPTANCE_TS TIMESTAMP,
  CREDIT_ASSESSMENT_ID BIGINT,
  APPROVAL_DT TIMESTAMP,
  APPROVAL_EXTERNAL_ID BIGINT,
  MEMO_TYPE_CD VARCHAR,
  VALID_START_TS TIMESTAMP,
  VALID_END_TS TIMESTAMP,
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  CREATED_BY VARCHAR,
  CREATED_ON_TS TIMESTAMP DEFAULT NOW(),
  UPDATED_BY VARCHAR,
  UPDATED_ON_TS TIMESTAMP DEFAULT NOW(),
  VERSION INT DEFAULT 1,
  CONSTRAINT PK_CRWH_WARNING_ID PRIMARY KEY (WARNING_ID),
  CONSTRAINT FK_CRHI_CREDIT_PROFILE_ID FOREIGN KEY (CREDIT_PROFILE_ID) REFERENCES CRPROFL.CREDIT_PROFILE (CREDIT_PROFILE_ID)
);

CREATE TABLE CRPROFL.CUSTOMER_CREDIT_PROFILE_REL (
  CREDIT_PROFILE_CUSTOMER_ID UUID NOT NULL,
  CREDIT_PROFILE_ID UUID NOT NULL,
  ORIGINATOR_APP_ID VARCHAR,
  CHANNEL_ORG_ID VARCHAR,
  CREATED_BY VARCHAR,
  CREATED_ON_TS TIMESTAMP DEFAULT NOW(),
  UPDATED_BY VARCHAR,
  UPDATED_ON_TS TIMESTAMP DEFAULT NOW(),
  VERSION INT DEFAULT 1,
  COLUMN CUSTOMER_CREDIT_PROFILE_REL_CD VARCHAR,
  "role" VARCHAR,  
  CONSTRAINT PK_CCRL_CUSTID_CPROID PRIMARY KEY (CREDIT_PROFILE_CUSTOMER_ID, CREDIT_PROFILE_ID),
  CONSTRAINT FK_CCRL_CREDIT_PROFILE_CUSTOMER_ID FOREIGN KEY (CREDIT_PROFILE_CUSTOMER_ID) REFERENCES CRPROFL.CUSTOMER (CREDIT_PROFILE_CUSTOMER_ID),
  CONSTRAINT FK_CCRL_CREDIT_PROFILE_ID FOREIGN KEY (CREDIT_PROFILE_ID) REFERENCES CRPROFL.CREDIT_PROFILE (CREDIT_PROFILE_ID)
);

CREATE TABLE CRPROFL.READDB_SYNC_STATUS (
  CREDIT_PROFILE_CUSTOMER_ID UUID,
  NEED_TO_SYNC BOOLEAN DEFAULT FALSE,
  NEED_TO_ENCRYPT BOOLEAN DEFAULT FALSE,
  NEED_TO_HASH BOOLEAN DEFAULT FALSE,
  NOTES VARCHAR,
  DATA TEXT,
  UPDATED_BY VARCHAR,
  UPDATED_ON_TS TIMESTAMP DEFAULT NOW(),
  CONSTRAINT PK_DBSY_CREDIT_PROFILE_CUSTOMER_ID PRIMARY KEY (CREDIT_PROFILE_CUSTOMER_ID),
  CONSTRAINT FK_RDBSS_CREDIT_PROFILE_CUSTOMER_ID FOREIGN KEY (CREDIT_PROFILE_CUSTOMER_ID) REFERENCES CRPROFL.CUSTOMER (CREDIT_PROFILE_CUSTOMER_ID)
);

CREATE TABLE CRPROFL.CONFIGPARAM (
  KEY VARCHAR NOT NULL,
  VALUE VARCHAR NOT NULL,
  NOTES VARCHAR
);


-------------------------------------------------------------------

-- Initial Data
INSERT INTO CRPROFL.IDENTIFICATION_ATTRIBUTES(ATTRIBUTE_NAME, IS_ENCRYPTED, CREATED_BY) VALUES ('provinceCd', false, 'SYSTEM');
INSERT INTO CRPROFL.IDENTIFICATION_ATTRIBUTES(ATTRIBUTE_NAME, IS_ENCRYPTED, CREATED_BY) VALUES ('identificationId', true, 'SYSTEM');
INSERT INTO CRPROFL.IDENTIFICATION_ATTRIBUTES(ATTRIBUTE_NAME, IS_ENCRYPTED, CREATED_BY) VALUES ('countryCd', false, 'SYSTEM');
INSERT INTO CRPROFL.IDENTIFICATION_ATTRIBUTES(ATTRIBUTE_NAME, IS_ENCRYPTED, CREATED_BY) VALUES ('issuingAuthority', false, 'SYSTEM');
INSERT INTO CRPROFL.IDENTIFICATION_ATTRIBUTES(ATTRIBUTE_NAME, IS_ENCRYPTED, CREATED_BY) VALUES ('issuingDate', false, 'SYSTEM');

