ALTER TABLE CRPROFL.CREDIT_PROFILE
ADD COLUMN APPLICATION_SUB_PROV_CD VARCHAR,
ADD COLUMN CREDIT_CHECK_CONSENT_CD VARCHAR,
ADD COLUMN LINE_OF_BUSINESS VARCHAR,
ADD COLUMN CREDIT_PROFILE_STATUS_CD VARCHAR,
ADD COLUMN CREDIT_PROFILE_STATUS_TS VARCHAR;

ALTER TABLE CRPROFL.CUSTOMER_CREDIT_PROFILE_REL ADD COLUMN CUSTOMER_CREDIT_PROFILE_REL_CD VARCHAR;
ALTER TABLE CRPROFL.CUSTOMER ADD COLUMN "role" VARCHAR; -- ROLE is a reserved keyword and placed under quotes and has to be in lower case



ALTER TABLE CRPROFL.CUSTOMER  ADD COLUMN PARTY_ID UUID ;
ALTER TABLE CRPROFL.CUSTOMER ALTER COLUMN PARTY_ID drop not null;
ALTER TABLE CRPROFL.CUSTOMER  ADD CONSTRAINT FK_CUST_PARTY_ID  FOREIGN KEY (PARTY_ID)  REFERENCES CRPROFL.PARTY (PARTY_ID)



ALTER TABLE CRPROFL.ORGANIZATION
ADD COLUMN BIRTH_DATE DATE;