ALTER TABLE CRPROFL.CREDIT_PROFILE
ADD COLUMN POPULATE_METHOD_CD VARCHAR(18),
ADD COLUMN CPROFL_FORMAT_CD VARCHAR(18),
ADD COLUMN COMMENT_TXT VARCHAR(1000),
ADD COLUMN BUS_LAST_UPDT_TS TIMESTAMP,
ADD COLUMN BYPASS_MATCH_IND BOOLEAN,
ADD COLUMN PRODUCT_CATEGORY_BOLT_ON BOOLEAN;


ALTER TABLE CRPROFL.INDIVIDUAL
ADD COLUMN EMPLOYMENT_STATUS_CD VARCHAR(18),
ADD COLUMN LEGAL_CARE_CD VARCHAR(18),
ADD COLUMN PRIM_CRED_CARD_TYP_CD VARCHAR(18),
ADD COLUMN RESIDENCY_CD VARCHAR(18),
ADD COLUMN SEC_CRED_CARD_ISS_CO_TYP_CD VARCHAR(18);




CREATE TABLE CRPROFL.PROD_QUAL (
  PRODUCT_QUAL_ID UUID DEFAULT uuid_generate_v4(),
  PRODUCT_QUAL_LEGACY_ID BIGINT,
  CREDIT_APPRVD_PROD_CATGY_CD VARCHAR(18),
  CREDIT_PROFILE_ID UUID NOT NULL,
  PRODUCT_QUAL_IND BOOLEAN,
  VALID_START_TS TIMESTAMP,
  VALID_END_TS TIMESTAMP,
  ORIGINATOR_APP_ID VARCHAR,
  CREATED_BY VARCHAR,
  CREATED_ON_TS TIMESTAMP DEFAULT NOW(),
  UPDATED_BY VARCHAR,
  UPDATED_ON_TS TIMESTAMP DEFAULT NOW(),
  VERSION INT DEFAULT 1,
  CONSTRAINT PK_PROD_QUAL_ID PRIMARY KEY (PRODUCT_QUAL_ID ),
  CONSTRAINT FK_PROD_QUAL_CREDIT_PROFILE_ID FOREIGN KEY (CREDIT_PROFILE_ID) REFERENCES CRPROFL.CREDIT_PROFILE (CREDIT_PROFILE_ID)
);

ALTER TABLE CRPROFL.PARTY
ADD COLUMN STATUS_CD  VARCHAR(2);





CREATE TABLE CRPROFL.CPROFL_MAPPING 
   (	
	CPROFL_MAPPING_ID  UUID DEFAULT uuid_generate_v4(), 
	CUSTOMER_ID BIGINT NOT NULL,
	CPROFL_TO_ID  UUID NOT NULL , 
	CPROFL_FROM_ID UUID  NOT NULL , 
	CPROFL_MAPPING_TYP_CD VARCHAR(2) NOT NULL , 

	ORIGINATOR_APP_ID VARCHAR,
	CHANNEL_ORG_ID VARCHAR,
	CREATED_BY VARCHAR,
	CREATED_ON_TS TIMESTAMP DEFAULT NOW(),
	UPDATED_BY VARCHAR,
	UPDATED_ON_TS TIMESTAMP DEFAULT NOW(),
	
	VERSION INT DEFAULT 1,
	
	CONSTRAINT CPROFL_MAPPING_PK PRIMARY KEY (CPROFL_MAPPING_ID)
	)



